services:
  proxy:
    container_name: torprivoxy
    image: avpnusr/torprivoxy
    restart: unless-stopped
    hostname: proxy
    networks:
      - internal_network
    ports:
      - "${PRIVOXY_PORT}:8118" # Privoxy port
      - "${TOR_SOCKS_PORT}:9050" # Tor SOCKS port
    environment:
      TOR_CONTROL_PASSWORD: "${TOR_CONTROL_PASSWORD}"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8118/"]
      interval: "${HEALTHCHECK_INTERVAL}"
      timeout: "${HEALTHCHECK_TIMEOUT}"
      retries: "${HEALTHCHECK_RETRIES}"

  changedetection:
    container_name: changedetection
    image: ghcr.io/dgtlmoon/changedetection.io:latest
    restart: unless-stopped
    volumes:
      - ./datastore:/datastore
    ports:
      - "${CHANGEDETECTION_PORT}:5000"
    networks:
      - internal_network
    environment:
      HIDE_REFERER: "true"
      PLAYWRIGHT_DRIVER_URL: "${PLAYWRIGHT_CHROME_URL}"
      FETCH_BACKEND: "html_webdriver"
      DEFAULT_FETCH_BACKEND: "html_webdriver"
      HTTP_PROXY: "http://proxy:${PRIVOXY_PORT}"
      HTTPS_PROXY: "http://proxy:${PRIVOXY_PORT}"
      NO_PROXY: "localhost,127.0.0.1"
      SOCKS_HOST: "proxy"
      SOCKS_PORT: "${TOR_SOCKS_PORT}"
      REQUESTS_CA_BUNDLE: "/etc/ssl/certs/ca-certificates.crt"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: "${HEALTHCHECK_INTERVAL}"
      timeout: "${HEALTHCHECK_TIMEOUT}"
      retries: "${HEALTHCHECK_RETRIES}"
    depends_on:
      - proxy

  playwright-chrome:
    container_name: playwright
    image: browserless/chrome
    restart: unless-stopped
    environment:
      SCREEN_WIDTH: "1920"
      SCREEN_HEIGHT: "1080"
      SCREEN_DEPTH: "16"
      ENABLE_DEBUGGER: "false"
      PREBOOT_CHROME: "true"
      CONNECTION_TIMEOUT: "300000"
      MAX_CONCURRENT_SESSIONS: "10"
      CHROME_REFRESH_TIME: "600000"
      DEFAULT_BLOCK_ADS: "true"
      DEFAULT_STEALTH: "true"
      DEFAULT_IGNORE_HTTPS_ERRORS: "true"
      SCREENSHOT_FULLPAGE: "true"
      STATS_REFRESH_SECONDS: "120"
      HTTP_PROXY: "http://proxy:${PRIVOXY_PORT}"
      HTTPS_PROXY: "http://proxy:${PRIVOXY_PORT}"
      NO_PROXY: "localhost,127.0.0.1"
    tmpfs:
      - /tmp
    networks:
      - internal_network
    depends_on:
      - proxy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: "${HEALTHCHECK_INTERVAL}"
      timeout: "${HEALTHCHECK_TIMEOUT}"
      retries: "${HEALTHCHECK_RETRIES}"

  main-app:
    container_name: nextjs-app
    build:
      context: ./main-app
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - internal_network
    depends_on:
      changedetection:
        condition: service_started
      proxy:
        condition: service_started
      postgres:
        condition: service_healthy
    environment:
      NEXT_PUBLIC_API_URL: "${CHANGEDETECTION_URL}" # Point to the changedetection.io service
      CHANGEDETECTION_URL: "${CHANGEDETECTION_URL}" # Internal URL for API access
      NEXT_TELEMETRY_DISABLED: "1"
      NODE_ENV: "production"
      DATABASE_URL: "postgresql://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_NAME}"
      # SMTP Configuration - Can be set via .env file or when running docker-compose
      SMTP_HOST: ${SMTP_HOST:-}
      SMTP_PORT: ${SMTP_PORT:-}
      SMTP_USER: ${SMTP_USER:-}
      SMTP_PASSWORD: ${SMTP_PASSWORD:-}
      SMTP_FROM: ${SMTP_FROM:-}
      SMTP_SECURE: ${SMTP_SECURE:-false}
    ports:
      - "${NEXTJS_PORT}:3000" # Expose the Next.js service

  postgres:
    container_name: postgres
    image: postgres:16-alpine
    restart: unless-stopped
    networks:
      - internal_network
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_NAME}"
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "${POSTGRES_PORT}:5432" # Postgres port
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d changedetection"]
      interval: "${DB_HEALTHCHECK_INTERVAL}"
      timeout: "${DB_HEALTHCHECK_TIMEOUT}"
      retries: "${DB_HEALTHCHECK_RETRIES}"

volumes:
  changedetection-data:
  postgres-data:

networks:
  internal_network:
