graph TD
    Internet1[Internet] -->|port 80/443| Nginx
    Nginx -->|reverse proxy| MainApp[Main-App]
    Nginx -->|reverse proxy| ChangeDetection
    MainApp --> Postgres
    ChangeDetection --> PlaywrightChrome[Playwright-Chrome]
    ChangeDetection --> TorPrivoxy
    PlaywrightChrome --> TorPrivoxy
    TorPrivoxy --> Internet2[Internet]
    
    subgraph public_network [Public Network]
        Nginx
    end
    
    subgraph change_network [Change Network]
        MainApp
        ChangeDetection
        Nginx
    end
    
    subgraph db_network [Database Network]
        MainApp
        Postgres
    end
    
    subgraph browser_network [Browser Network]
        ChangeDetection
        PlaywrightChrome
    end
    
    subgraph proxy_network [Proxy Network]
        ChangeDetection
        PlaywrightChrome
        TorPrivoxy
    end
    
    subgraph tor_network [Tor Network]
        TorPrivoxy
    end
    
    classDef external fill:#f96,stroke:#333,stroke-width:2px;
    classDef internal fill:#9cf,stroke:#333,stroke-width:1px;
    class Internet1,Internet2 external;
    class Nginx,MainApp,ChangeDetection,PlaywrightChrome,Postgres,TorPrivoxy internal;
